<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="PDFsharp" />
  </ItemGroup>

  <ItemGroup>
    <None Include="../../fonts/**/*.ttf;../../fonts/**/*.txt" Link="fonts/%(RecursiveDir)%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
